# Generated by Django 5.2 on 2025-04-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0014_customautofieldmodel_custombigautofieldmodel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompositePkModel",
            fields=[
                ("id1", models.IntegerField()),
                ("id2", models.IntegerField()),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "id1",
                        "id2",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
    ]
