# Generated by Django 4.2.6 on 2025-04-21 20:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0015_compositepkmodel"),
        ("tests", "0016_condstatement_condstatementevent_and_more"),
    ]

    operations = []
