site_name: django-pghistory
docs_dir: docs

repo_name: AmbitionEng/django-pghistory
repo_url: https://github.com/AmbitionEng/django-pghistory

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          import:
          - https://docs.python.org/3/objects.inv
          - https://installer.readthedocs.io/en/stable/objects.inv
          - https://mkdocstrings.github.io/autorefs/objects.inv
          options:
            docstring_options:
              ignore_init_summary: true
            line_length: 80
            heading_level: 2
            merge_init_into_class: true
            separate_signature: true
            show_root_heading: true
            show_root_full_path: true
            show_root_members_full_path: true
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true

markdown_extensions:
  # For admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true

theme:
  custom_dir: docs/overrides
  name: material
  logo: static/dark_logo.png
  favicon: static/light_logo.png
  features:
    - content.code.copy
    - navigation.footer
    - navigation.path
    - navigation.sections
    - navigation.tracking
    - search.suggest
    - search.highlight
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - css/mkdocstrings.css
  - css/mkdocs-material.css

nav:
  - Overview: index.md
  - Installation: installation.md
  - Usage Guides:
      - Basics: basics.md
      - Event Tracking: event_tracking.md
      - Collecting Context: context.md
      - Event Models: event_models.md
      - Aggregating Events and Diffs: aggregating_events.md
      - Admin Integration: admin.md
      - Reverting Objects: reversion.md
  - Help:
      - FAQ: faq.md
      - Troubleshooting: troubleshooting.md
      - Performance and Scaling: performance.md
      - Upgrading: upgrading.md
  - API:
      - Settings: settings.md
      - Reference: module.md
      - Release Notes: release_notes.md
      - Contributing Guide: contributing.md
